const defines = {
    SERVER_URL: "http://localhost:4000",
    ROOT_URL: "/",
    LOGIN_URL: "/login",
    SIGNUP_URL: "/signup",
    REGISTER_URL: "/register",
    HOME_URL: "/app/home",
    PROFIL_URL: "/app/profil",
    PROFIL_IMG_URL: "/app/profil/img",
    PROFIL_DESC_URL: "/app/profil/description",
    PROFIL_PASSWD_URL: "/app/profil/password",
    PROFIL_ACC_URL: "/app/profil/account",
    TEAM_URL: "/app/team",
    NOTIFICATION_URL: "/app/notification",
    LOGOUT_URL: "/app/logout",
    PUBLISH_URL: "/app/publish",
    PUBLISH_LIKE_URL: "/app/publish/like",
    PUBLISH_DISLIKE_URL: "/app/publish/dislike",
    PUBLISH_DEL_URL: "/app/publish/delete",
    COMMENT_URL: "/app/publish/comment",
    COMMENT_DEL_URL: "/app/publish/comment/delete",
    AUTO_LOG_URL: "/app/autolog",
    UNKNOWN_URL: "/*",
};

module.exports = defines;