const defines = {
    // urls
    SERVER_URL: "http://localhost:4000",
    ROOT_URL: "/",
    LOGIN_URL: "/login",
    SIGNUP_URL: "/signup",
    REGISTER_URL: "/register",
    HOME_URL: "/app/home",
    PROFIL_URL: "/app/profil",
    PROFIL_IMG_URL: "/app/profil/img",
    PROFIL_DESC_URL: "/app/profil/description",
    PROFIL_PASSWD_URL: "/app/profil/password",
    PROFIL_ACC_URL: "/app/profil/account",
    PROFIL_MODE_URL: "/app/profil/mode",
    LOCK_USER_URL: "/app/profil/lock",
    UNLOCK_USER_URL: "/app/profil/unlock",
    PASSWORD_URL: "/app/password",
    TEAM_URL: "/app/team",
    USERS_URL: "/app/team/users",
    NOTIFICATION_URL: "/app/notification/notifs",
    DEL_NOTIFICATION_URL: "/app/notification/delete",
    READ_NOTIFICATION_URL: "/app/notification/read",
    LOGOUT_URL: "/app/logout",
    PUBLISH_URL: "/app/publish",
    PUBLISH_SCROLL_URL: "/app/publish/scroll",
    PUBLISH_LIKE_URL: "/app/publish/like",
    PUBLISH_DISLIKE_URL: "/app/publish/dislike",
    PUBLISH_UNLIKE_URL: "/app/publish/unlike",
    PUBLISH_UNDISLIKE_URL: "/app/publish/undislike",
    PUBLISH_DEL_URL: "/app/publish/delete",
    COMMENT_URL: "/app/publish/comment",
    COMMENT_DEL_URL: "/app/publish/comment/delete",
    AUTO_LOG_URL: "/app/autolog",
    IMG_URL: "/app/img",
    TOKEN_URL: "/app/token",
    DEL_ACCOUNT_URL: "/app/account",
    DEF_SU_IMG_URL: "/img/super_user.png",
    SUPER_USER_URL: "/app/authorize/super",
    REVOKE_SUPER_USER_URL: "/app/authorize/revoke",
    READ_ALL_URL: "/app/notification/readall",
    DELETE_ALL_URL: "/app/notification/deleteall",
    UNKNOWN_URL: "/*",
    // variables
    TIMEOUT: 1000,
};

module.exports = defines;